# Generated by Django 3.2 on 2023-06-04 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=500)),
                ('colors', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
